-- MySQL Script generated by MySQL Workbench
-- Mon Nov 21 18:59:18 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TiendaUnidos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TiendaUnidos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TiendaUnidos` DEFAULT CHARACTER SET latin1 ;
USE `TiendaUnidos` ;

-- -----------------------------------------------------
-- Table `TiendaUnidos`.`Carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TiendaUnidos`.`Carrito` (
  `CarritoID` INT(11) NOT NULL AUTO_INCREMENT,
  `NumeroProductos` INT(11) NOT NULL,
  `PrecioTotal` INT(11) NOT NULL,
  PRIMARY KEY (`CarritoID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TiendaUnidos`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TiendaUnidos`.`Categoria` (
  `CategoriaID` INT(11) NOT NULL AUTO_INCREMENT,
  `NombreCat` VARCHAR(20) NOT NULL,
  `Descripcion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`CategoriaID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TiendaUnidos`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TiendaUnidos`.`Producto` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NombreProducto` VARCHAR(20) NOT NULL,
  `Descuento` INT(11) NULL DEFAULT NULL,
  `UnidadesEnOrden` INT(11) NOT NULL,
  `UnidadesEnAlmacen` INT(11) NOT NULL,
  `PrecioPorUnidad` INT(11) NOT NULL,
  `CatntidadPorUnidad` INT(11) NOT NULL,
  `DescripcionProducto` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TiendaUnidos`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TiendaUnidos`.`Usuario` (
  `UsuarioID` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NOT NULL,
  `Apellido` VARCHAR(20) NOT NULL,
  `Pass` VARCHAR(20) NOT NULL,
  `Admin` TINYINT(1) NOT NULL,
  PRIMARY KEY (`UsuarioID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TiendaUnidos`.`informacionpago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TiendaUnidos`.`informacionpago` (
  `InfoPagoID` INT(11) NOT NULL AUTO_INCREMENT,
  `FechaPago` VARCHAR(10) NOT NULL,
  `Direccion` VARCHAR(20) NOT NULL,
  `ExpiracionTjt` VARCHAR(10) NOT NULL,
  `PinTarjeta` VARCHAR(5) NOT NULL,
  `NumeroTarjeta` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`InfoPagoID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TiendaUnidos`.`informacionpersonal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TiendaUnidos`.`informacionpersonal` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Telefono` VARCHAR(20) NOT NULL,
  `Correo` VARCHAR(20) NOT NULL,
  `Ciudad` VARCHAR(20) NOT NULL,
  `Pais` VARCHAR(20) NOT NULL,
  `Direccion` VARCHAR(20) NOT NULL,
  `CodigoPostal` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TiendaUnidos`.`orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TiendaUnidos`.`orden` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `UsuarioID` INT(11) NOT NULL,
  `NumOrden` INT(11) NOT NULL,
  `FechaOrden` VARCHAR(20) NOT NULL,
  `FechaRequerida` VARCHAR(20) NOT NULL,
  `FechaEnvio` VARCHAR(20) NOT NULL,
  `MetodoEnvio` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `UsuarioID` (`UsuarioID` ASC),
  CONSTRAINT `orden_ibfk_1`
    FOREIGN KEY (`UsuarioID`)
    REFERENCES `TiendaUnidos`.`Usuario` (`UsuarioID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TiendaUnidos`.`orderdetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TiendaUnidos`.`orderdetail` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ProductoID` INT(11) NOT NULL,
  `Precio` INT(11) NOT NULL,
  `Cantidad` INT(11) NOT NULL,
  `NumeroDeOrden` INT(11) NOT NULL,
  `Descuento` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ProductoID` (`ProductoID` ASC),
  CONSTRAINT `orderdetail_ibfk_1`
    FOREIGN KEY (`ProductoID`)
    REFERENCES `TiendaUnidos`.`Producto` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
